#!/bin/bash

TOTP_MODE=${LAZY_CONNECT_TOTP_GENERATOR:-oathtool}

_lazy_connect_config_dir=~/.config/lazy-connect
_lazy_connect_project_dir=~/.lazy-connect

function _lazy_connect_init() {
  case $TOTP_MODE in
  oathtool)
    echo -n "Secret Key: "
    read -s secret_key
    echo "**********"

    echo 'Storing secret in keychain...'
    old_secret=~/.config/lazy-connect/secret
    [ -f "$old_secret" ] && rm "$old_secret"
    security delete-generic-password -a lazy-connect -s lazy-connect &>/dev/null
    security add-generic-password -a lazy-connect -p "$secret_key" -s lazy-connect
    ;;
  esac
  _lazy_connect_vpn_refresh
}

function _lazy_connect_vpn_refresh() {
  local backup_file=/tmp/lazy-connect-vpns-$(date +%-H-%M-%S-%F)
  [ -f $_lazy_connect_config_dir/vpns ] && cp $_lazy_connect_config_dir/vpns $backup_file
  osascript <<EOF |
    tell application "System Events"
      tell process "SystemUIServer"
        set vpnMenu to (menu bar item 1 of menu bar 1 where description is "VPN")
        tell vpnMenu to click
        set vpnMenuItems to (menu items of menu 1 of vpnMenu)
        -- Loop till first missing value(that is fisrt menu item seperator) and accumulate VPN Names
        set vpnNames to {}
        repeat with vpnMenuItem in vpnMenuItems
          set vpnName to name of vpnMenuItem
          if vpnName is equal to missing value then
            exit repeat
          end if
          set vpnNames to vpnNames & {vpnName}
        end repeat
        key code 53
        get vpnNames
      end tell
    end tell
EOF
    tr ',' '\n' | sed 's/^[[:space:]]//g' | cut -d' ' -f2- >$_lazy_connect_config_dir/vpns

  echo "Storing the VPN list..."
  if [ -f $backup_file ]; then
    echo -e "\nDiff:\n$(diff -y $backup_file $_lazy_connect_config_dir/vpns)"
  else
    echo -e "\nVPN List:"
    cat $_lazy_connect_config_dir/vpns | nl
  fi
}

function _lazy_connect_usage() {
  cat <<EOF

USAGE:

lazy-connect - Shell function to fuzzy search an IPSec VPN by name
               and connect to it automatically.

-i    - Initialize lazy-connect. Stores the TOTP secret and VPN list.
-r    - Refresh vpn list in ~/.config/lazy-connect .
-y    - Select the last selected VPN.
-n    - Do not fill the password automatically. Instead copy the password to clipboard.
-h    - Show this help.
EOF
}

function _lazy_connect_get_totp() {
  secret_key=$1
  case $TOTP_MODE in
  oathtool)
    password=$(oathtool --totp --base32 $secret_key)
    return 0
    ;;
  yubikey)
    if ! [ -x "$(command -v ykman)" ]; then
      echo 'Error: ykman tool not installed.' >&2
      exit 1
    fi
    if [ -z "$LAZY_CONNECT_TOTP_QUERY" ]; then
      echo "Error: LAZY_CONNECT_TOTP_QUERY not set."
      exit 1
    else
      password=$(ykman oath code $LAZY_CONNECT_TOTP_QUERY 2>/dev/null | awk '{print $2}')
    fi
    ;;
  esac
}

function _lazy_connect() {
  vpn_name=$1
  _lazy_connect_get_totp $2
  local autofill=$3

  if [ -z "$password" ]; then
    case $TOTP_MODE in
    oathtool)
      echo "Error: Unable to generate otp using oathtool."
      return 1
      ;;
    yubikey)
      echo "Error: No YubiKey found."
      return 1
      ;;
    esac
  elif [ "$autofill" == "false" ]; then
    echo -n "$password" | pbcopy
  fi

  osascript <<EOF
    on connectVpn(vpnName, password, autofill)
      tell application "System Events"
        tell process "SystemUIServer"
          set vpnMenu to (menu bar item 1 of menu bar 1 where description is "VPN")
          tell vpnMenu to click
          try
            click menu item vpnName of menu 1 of vpnMenu
            if autofill is equal to "true" then
              delay 2
              keystroke password
              keystroke return
            end if
          on error errorStr
            if errorStr does not contain "Can’t get menu item" and errorStr does not contain vpnName then
              display dialog errorStr
            end if
          end try
        end tell
      end tell
    end connectVpn
    connectVpn("$vpn_name", "$password", "$autofill")
EOF
}

function _lazy_connect_mojave() {
  vpn_name=$1
  osx_vpn_name_not_connected="${vpn_name/Connect /}, Not Connected"
  osx_vpn_name_connected="${vpn_name/Connect /}, Connected"
  osx_vpn_name="${vpn_name/Connect /}"

  _lazy_connect_get_totp $2
  local autofill=$3

  if [ -z "$password" ]; then
    case $TOTP_MODE in
    oathtool)
      echo "Error: Unable to generate otp using oathtool."
      return 1
      ;;
    yubikey)
      echo "Error: No YubiKey found."
      return 1
      ;;
    esac
  elif [ "$autofill" == "false" ]; then
    echo -n "$password" | pbcopy
  fi

  osascript <<EOF
    on connectOrDisconnectVpn(vpnName, disconnectedVpnName, connectedVpnName, password)
      tell application "System Preferences"
        reveal pane "Network"
        activate
        tell application "System Events"
          tell process "System Preferences"
            tell window 1
              repeat with r in rows of table 1 of scroll area 1
                if (value of attribute "AXValue" of static text 1 of r as string) contains vpnName then
                  select r
                  exit repeat
                end if
              end repeat
              if (value of attribute "AXValue" of static text 1 of r as string) is equal to disconnectedVpnName then
                log "Connecting to vpn " & vpnName
                tell group 1
                  click button "Authentication Settings…"
                end tell
                tell sheet 1
                  set focused of text field 2 to true
                  set value of text field 2 to password
                  click button "Ok"
                end tell
                click button "Apply"
                delay 1
                tell group 1
                  click button "Connect"
                end tell
                log "Connected"
              else if (value of attribute "AXValue" of static text 1 of r as string) is equal to connectedVpnName then
                log "Disconnecting from vpn " & vpnName
                tell group 1
                  click button "Disconnect"
                end tell
                log "Disconnected"
              else
                log "Couldn't connect or disconnect the VPN, didn't find any exact match. The network found was: "
                log (value of attribute "AXValue" of static text 1 of r as string)
              end if
            end tell
          end tell
        end tell
        quit
      end tell
    end connectOrDisconnectVpn
    connectOrDisconnectVpn("$osx_vpn_name", "$osx_vpn_name_not_connected", "$osx_vpn_name_connected", "$password")
EOF
}

version_lte() {
    [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
}

version_lt() {
    [ "$1" = "$2" ] && return 1 || version_lte $1 $2
}

_get_last_selected_vpn() {
  if [ -f $_lazy_connect_config_dir/last_vpn ]; then
    last_vpn=$(cat $_lazy_connect_config_dir/last_vpn)
  fi
  if [ -z "$last_vpn" ]; then
    echo "0"
  else
    echo $last_vpn
  fi
}

function lazy-connect() {
  local OPTIND
  local autofill="true"
  local choose_last="false"
  mkdir -p $_lazy_connect_config_dir

  while getopts "irnhy" opt; do
    case $opt in
    h)
      _lazy_connect_usage
      return 0
      ;;
    i)
      _lazy_connect_init
      return 0
      ;;
    r)
      echo "Refreshing VPN list..."
      _lazy_connect_vpn_refresh
      return 0
      ;;
    n)
      autofill="false"
      shift $((OPTIND - 1))
      ;;
    y)
      choose_last="true"
      shift $((OPTIND - 1))
      ;;
    \?)
      echo "Invalid Option: -$OPTARG."
      _lazy_connect_usage
      return 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument."
      _lazy_connect_usage
      return 1
      ;;
    esac
  done

  local secret=$(security find-generic-password -a lazy-connect -w 2>/dev/null | tr -d '\n')
  if [ -z "$secret" ]; then
    echo "Secret not found in keychain. Initialize lazy-connect and try again."
    return 1
  fi

  last_vpn=$(_get_last_selected_vpn)
  if [ "true" == "$choose_last" -a "0" != "$last_vpn" ]; then
      vpn_name=$last_vpn
  else
    vpn_name=$(cat $_lazy_connect_config_dir/vpns |
      fzf --height=10 --ansi --reverse --query "$*" --select-1)
  fi

  mac_version=$(sw_vers -productVersion)
  is_less_than_mojave=$(version_lt $mac_version 10.14 && echo "yes" || echo "no")
  if [ $is_less_than_mojave = "yes" ]; then
    [ -z "$vpn_name" ] || _lazy_connect "$vpn_name" "$secret" "$autofill"
  else
    [ -z "$vpn_name" ] || _lazy_connect_mojave "$vpn_name" "$secret" "$autofill"
  fi
  echo -n $vpn_name > $_lazy_connect_config_dir/last_vpn
}

lazy-connect "$@"
